### ISSUE TITLE
Add command isn't working as expected

### ISSUE THREAD

**Issue by xuzaixian** [nestjs/azure-storage#297]

**Comment by micalevisk** [comment]
I'm getting another error:

```bash
$ npx nest add @nestjs/azure-storage
✔ Package installation in progress... ☕
Starting library setup...
Error: NOT SUPPORTED: keyword "id", use "$id" for schema ID
    at Object.code (/tmp/add-issue/node_modules/ajv/dist/vocabularies/core/id.js:6:15)
    at keywordCode (/tmp/add-issue/node_modules/ajv/dist/compile/validate/index.js:454:13)
    at /tmp/add-issue/node_modules/ajv/dist/compile/validate/index.js:222:17
    at CodeGen.code (/tmp/add-issue/node_modules/ajv/dist/compile/codegen/index.js:439:13)
    at CodeGen.block (/tmp/add-issue/node_modules/ajv/dist/compile/codegen/index.js:568:18)
    at iterateKeywords (/tmp/add-issue/node_modules/ajv/dist/compile/validate/index.js:219:9)
    at groupKeywords (/tmp/add-issue/node_modules/ajv/dist/compile/validate/index.js:208:13)
    at /tmp/add-issue/node_modules/ajv/dist/compile/validate/index.js:192:13
    at CodeGen.code (/tmp/add-issue/node_modules/ajv/dist/compile/codegen/index.js:439:13)
    at CodeGen.block (/tmp/add-issue/node_modules/ajv/dist/compile/codegen/index.js:568:18)
```

**Comment by xuzaixian** [comment]
> 

I think it's an another [issue](https://github.com/angular/angular-cli/issues/22637#issuecomment-1028161416)

**Comment by blowsie** [comment]
Same for me on windows

```
λ nest add @nestjs/azure-storage
√ Package installation in progress... ☕
Starting library setup...
Error: Collection "@nestjs/azure-storage" cannot be resolved.

Failed to execute command: node @nestjs/azure-storage:nest-add --source-root="src" C:\Users\xxx\scoop\apps\nvm\current\nodejs\nodejs\node.exe C:\Users\xxx\AppData\Local\pnpm\global\5\node_modules\@nestjs\cli\bin\nest.js add @nestjs/azure-storage

```
